In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Task A a load dataset
df=pd.read_excel('/content/drive/MyDrive/612 course/612 assessment 2/Adidas US Sales Datasets.xlsx')

In [4]:
df

,Unnamed: 0,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,NaN,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,NaN,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,NaN,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,NaN,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,NaN,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,NaN,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,NaN,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,NaN,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,NaN,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,NaN,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [ ]:
df.shape

(9648, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Retailer          9648 non-null   object
 2   Retailer ID       9648 non-null   int64
 3   Invoice Date      9648 non-null   datetime64[ns]
 4   Region            9648 non-null   object
 5   State             9648 non-null   object
 6   City              9648 non-null   object
 7   Product           9648 non-null   object
 8   Price per Unit    9648 non-null   float64
 9   Units Sold        9648 non-null   int64
 10  Total Sales       9648 non-null   float64
 11  Operating Profit  9648 non-null   float64
 12  Operating Margin  9648 non-null   float64
 13  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(2), object(6)
memory usage: 1.0+ MB

In [ ]:
df.describe()

,Unnamed: 0,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin
count,0.0,9.648000e+03,9648,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000
mean,NaN,1.173850e+06,2021-05-10 15:20:44.776119296,45.216625,256.930037,93273.437500,34425.244761,0.422991
min,NaN,1.128299e+06,2020-01-01 00:00:00,7.000000,0.000000,0.000000,0.000000,0.100000
25%,NaN,1.185732e+06,2021-02-17 00:00:00,35.000000,106.000000,4254.500000,1921.752500,0.350000
50%,NaN,1.185732e+06,2021-06-04 00:00:00,45.000000,176.000000,9576.000000,4371.420000,0.410000
75%,NaN,1.185732e+06,2021-09-16 00:00:00,55.000000,350.000000,150000.000000,52062.500000,0.490000
max,NaN,1.197831e+06,2021-12-31 00:00:00,110.000000,1275.000000,825000.000000,390000.000000,0.800000
std,NaN,2.636038e+04,NaN,14.705397,214.252030,141916.016727,54193.113713,0.097197

In [ ]:
df.columns

Index(['Unnamed: 0', 'Retailer', 'Retailer ID', 'Invoice Date', 'Region',
       'State', 'City', 'Product', 'Price per Unit', 'Units Sold',
       'Total Sales', 'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object')

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.isnull().sum()

Unnamed: 0          9648
Retailer               0
Retailer ID            0
Invoice Date           0
Region                 0
State                  0
City                   0
Product                0
Price per Unit         0
Units Sold             0
Total Sales            0
Operating Profit       0
Operating Margin       0
Sales Method           0
dtype: int64

In [ ]:
# Task A b transforms messy dataset into tidy data format
df.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
# Create 'Month' and 'Year' columns
df['Month'] = df['Invoice Date'].dt.month
df['Year'] = df['Invoice Date'].dt.year
# Display the updated DataFrame
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,1,2020
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,1,2020
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,1,2020
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,1,2020
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,1,2020

In [ ]:
# Function to find outliers using Z-score for a specific column
def find_outliers_zscore(df, column, threshold=3):
    mean = np.mean(df[column])
    std = np.std(df[column])
    z_scores = (df[column] - mean) / std
    outliers = np.abs(z_scores) > threshold
    return outliers

# Find outliers in 'Units Sold' column using Z-score
outliers = find_outliers_zscore(df, 'Units Sold')

# Print DataFrame with outliers marked
print("DataFrame with outliers in 'Units Sold' column:")
df[outliers]

DataFrame with outliers in 'Units Sold' column:

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,1,2020
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,1,2020
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,1,2020
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,1,2020
5,Foot Locker,1185732,2020-01-06,Northeast,New York,New York,Women's Apparel,50.0,1000,500000.0,125000.0,0.25,In-store,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2403,Sports Direct,1185732,2021-07-02,Southeast,North Carolina,Charlotte,Men's Street Footwear,65.0,1050,682500.0,273000.0,0.40,Online,7,2021
2409,Sports Direct,1185732,2021-08-03,Southeast,North Carolina,Charlotte,Men's Street Footwear,65.0,1025,666250.0,266500.0,0.40,Online,8,2021
2415,Sports Direct,1185732,2021-09-02,Southeast,North Carolina,Charlotte,Men's Street Footwear,55.0,925,508750.0,203500.0,0.40,Online,9,2021
2433,Sports Direct,1185732,2021-12-02,Southeast,North Carolina,Charlotte,Men's Street Footwear,70.0,975,682500.0,273000.0,0.40,Online,12,2021
2475,Amazon,1185732,2021-07-09,Midwest,Ohio,Columbus,Men's Street Footwear,65.0,900,585000.0,234000.0,0.40,Online,7,2021

In [ ]:
# Perform one-hot encoding for categorical variables
df_encoded = pd.get_dummies(df, columns=['Retailer','Region','State', 'City', 'Product', 'Sales Method'])
# Display the encoded DataFrame
df_encoded.head()

,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Month,Year,Retailer_Amazon,...,City_Wilmington,Product_Men's Apparel,Product_Men's Athletic Footwear,Product_Men's Street Footwear,Product_Women's Apparel,Product_Women's Athletic Footwear,Product_Women's Street Footwear,Sales Method_In-store,Sales Method_Online,Sales Method_Outlet
0,1185732,2020-01-01,50.0,1200,600000.0,300000.0,0.50,1,2020,False,...,False,False,False,True,False,False,False,True,False,False
1,1185732,2020-01-02,50.0,1000,500000.0,150000.0,0.30,1,2020,False,...,False,False,True,False,False,False,False,True,False,False
2,1185732,2020-01-03,40.0,1000,400000.0,140000.0,0.35,1,2020,False,...,False,False,False,False,False,False,True,True,False,False
3,1185732,2020-01-04,45.0,850,382500.0,133875.0,0.35,1,2020,False,...,False,False,False,False,False,True,False,True,False,False
4,1185732,2020-01-05,60.0,900,540000.0,162000.0,0.30,1,2020,False,...,False,True,False,False,False,False,False,True,False,False

In [ ]:
# Convert only the encoded columns to integer (0 or 1)
df_encoded[df_encoded.columns] = df_encoded[df_encoded.columns].astype(int)

In [ ]:
print(df_encoded.dtypes)

Retailer ID                          int64
Invoice Date                         int64
Price per Unit                       int64
Units Sold                           int64
Total Sales                          int64
                                     ...
Product_Women's Athletic Footwear    int64
Product_Women's Street Footwear      int64
Sales Method_In-store                int64
Sales Method_Online                  int64
Sales Method_Outlet                  int64
Length: 131, dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# perform standardization on encoded dataset
numeric_columns = [col for col in df_encoded.columns if col not in ['Invoice Date', 'Month', 'Year']]
scaler = StandardScaler()
df_encoded[numeric_columns] = scaler.fit_transform(df_encoded[numeric_columns])
df_encoded.head()

,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Month,Year,Retailer_Amazon,...,City_Wilmington,Product_Men's Apparel,Product_Men's Athletic Footwear,Product_Men's Street Footwear,Product_Women's Apparel,Product_Women's Athletic Footwear,Product_Women's Street Footwear,Sales Method_In-store,Sales Method_Online,Sales Method_Outlet
0,0.450786,1577836800000000000,0.327800,4.401913,3.570794,4.900777,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,2.234401,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485
1,0.450786,1577923200000000000,0.327800,3.468385,2.866116,2.132759,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,2.234401,-0.447547,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485
2,0.450786,1578009600000000000,-0.352596,3.468385,2.161437,1.948225,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,-0.447547,-0.447214,-0.446880,2.236068,2.13186,-1.013566,-0.67485
3,0.450786,1578096000000000000,-0.012398,2.768238,2.038118,1.835197,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,-0.447547,-0.447214,2.237738,-0.447214,2.13186,-1.013566,-0.67485
4,0.450786,1578182400000000000,1.008197,3.001621,3.147987,2.354201,0.0,1,2020,-0.330292,...,-0.123091,2.237738,-0.447547,-0.447547,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485

In [ ]:
df_encoded['Invoice Date'] = pd.to_datetime(df_encoded['Invoice Date'])

In [ ]:
# Task A c
df_encoded.head()

,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Month,Year,Retailer_Amazon,...,City_Wilmington,Product_Men's Apparel,Product_Men's Athletic Footwear,Product_Men's Street Footwear,Product_Women's Apparel,Product_Women's Athletic Footwear,Product_Women's Street Footwear,Sales Method_In-store,Sales Method_Online,Sales Method_Outlet
0,0.450786,2020-01-01,0.327800,4.401913,3.570794,4.900777,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,2.234401,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485
1,0.450786,2020-01-02,0.327800,3.468385,2.866116,2.132759,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,2.234401,-0.447547,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485
2,0.450786,2020-01-03,-0.352596,3.468385,2.161437,1.948225,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,-0.447547,-0.447214,-0.446880,2.236068,2.13186,-1.013566,-0.67485
3,0.450786,2020-01-04,-0.012398,2.768238,2.038118,1.835197,0.0,1,2020,-0.330292,...,-0.123091,-0.446880,-0.447547,-0.447547,-0.447214,2.237738,-0.447214,2.13186,-1.013566,-0.67485
4,0.450786,2020-01-05,1.008197,3.001621,3.147987,2.354201,0.0,1,2020,-0.330292,...,-0.123091,2.237738,-0.447547,-0.447547,-0.447214,-0.446880,-0.447214,2.13186,-1.013566,-0.67485

In [ ]:
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,1,2020
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,1,2020
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,1,2020
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,1,2020
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,1,2020

In [ ]:
# Task A d
# Sort DataFrame by 'Operating Margin' in ascending order
df_sorted = df.sort_values(by='Operating Margin', ascending=True)
# Print sorted DataFrame
print("Sorted DataFrame by 'Operating Margin':")
df_sorted

Sorted DataFrame by 'Operating Margin':

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
199,West Gear,1128299,2021-02-04,West,California,San Francisco,Women's Apparel,70.0,700,490000.0,49000.00,0.10,Outlet,2,2021
211,West Gear,1128299,2021-02-16,West,California,San Francisco,Women's Apparel,70.0,800,560000.0,56000.00,0.10,Outlet,2,2021
205,West Gear,1128299,2021-02-10,West,California,San Francisco,Women's Apparel,70.0,775,542500.0,54250.00,0.10,Outlet,2,2021
193,West Gear,1128299,2021-01-29,West,California,San Francisco,Women's Apparel,70.0,775,542500.0,54250.00,0.10,Outlet,1,2021
7975,West Gear,1128299,2021-02-04,West,California,San Francisco,Women's Apparel,46.0,224,10304.0,1236.48,0.12,Outlet,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5017,Sports Direct,1197831,2021-09-23,South,Alabama,Birmingham,Women's Apparel,37.0,150,5550.0,4273.50,0.77,Online,9,2021
4494,West Gear,1128299,2020-04-18,West,Colorado,Denver,Men's Apparel,66.0,91,6006.0,4624.62,0.77,Online,4,2020
5029,Sports Direct,1197831,2021-10-05,South,Alabama,Birmingham,Women's Apparel,56.0,188,10528.0,8317.12,0.79,Online,10,2021
5035,Sports Direct,1197831,2021-10-11,South,Alabama,Birmingham,Women's Apparel,68.0,203,13804.0,11043.20,0.80,Online,10,2021
5005,Sports Direct,1197831,2021-09-11,South,Alabama,Birmingham,Women's Apparel,56.0,240,13440.0,10752.00,0.80,Online,9,2021

In [ ]:
df_filtered = df.query('`Operating Margin` > 0.40')
df_filtered

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store,1,2020
6,Foot Locker,1185732,2020-01-07,Northeast,New York,New York,Men's Street Footwear,50.0,1250,625000.0,312500.00,0.50,In-store,1,2020
12,Foot Locker,1185732,2020-01-25,Northeast,New York,New York,Men's Street Footwear,50.0,1220,610000.0,305000.00,0.50,Outlet,1,2020
18,Foot Locker,1185732,2020-01-31,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,Outlet,1,2020
24,Foot Locker,1185732,2020-02-06,Northeast,New York,New York,Men's Street Footwear,60.0,1220,732000.0,366000.00,0.50,Outlet,2,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9628,Foot Locker,1185732,2021-11-18,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,114,4788.0,2058.84,0.43,Outlet,11,2021
9632,Foot Locker,1185732,2021-11-18,Northeast,New Hampshire,Manchester,Women's Apparel,61.0,120,7320.0,3001.20,0.41,Outlet,11,2021
9633,Foot Locker,1185732,2021-12-17,Northeast,New Hampshire,Manchester,Men's Street Footwear,49.0,200,9800.0,4606.00,0.47,Outlet,12,2021
9634,Foot Locker,1185732,2021-12-17,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,49.0,128,6272.0,2634.24,0.42,Outlet,12,2021
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet,2,2021

In [ ]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp310-cp310-manylinux_2_17_x86_64.whl (19.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 45.3 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [ ]:
import mysql.connector
from mysql.connector import Error
from sqlalchemy import create_engine
from sqlalchemy import create_engine, text

In [ ]:
# Task A e establish connection with MySQL
username = 'root'
password = '900122tlT'
host = 'localhost'
new_database = '612_Assessment2'

# create connection
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}')

# Establish the connection
try:
    # Connect to the database
    with engine.connect() as connection:
        # Check the connection by executing a simple query
        connection.execute(text("SELECT 1"))
        print("Successfully connected to the MySQL database.")
except Exception as e:
    print(f"Failed to connect to the MySQL database. Error: {e}")

Failed to connect to the MySQL database. Error: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)
(Background on this error at: https://sqlalche.me/e/20/4xp6)

In [ ]:
# create database
with engine.connect() as connection:
    connection.execute(text(f"CREATE DATABASE IF NOT EXISTS {new_database}"))

In [ ]:
# Update the engine to use the new database
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}/{new_database}')
#Task A f import dataset into database
df.to_sql(name='Adidas', con=engine, if_exists='replace', index=False)
print("Dataset imported successfully into the 'Adidas' table.")

Dataset imported successfully into the 'Adidas' table.

In [ ]:
#Task A g retrieve and display
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM Adidas LIMIT 10"))
for row in result:
  print(row)

('Foot Locker', 1185732, datetime.datetime(2020, 1, 1, 0, 0), 'Northeast', 'New York', 'New York', "Men's Street Footwear", 50.0, 1200, 600000.0, 300000.0, 0.5, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 2, 0, 0), 'Northeast', 'New York', 'New York', "Men's Athletic Footwear", 50.0, 1000, 500000.0, 150000.0, 0.3, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 3, 0, 0), 'Northeast', 'New York', 'New York', "Women's Street Footwear", 40.0, 1000, 400000.0, 140000.0, 0.35, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 4, 0, 0), 'Northeast', 'New York', 'New York', "Women's Athletic Footwear", 45.0, 850, 382500.0, 133875.0, 0.35, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 5, 0, 0), 'Northeast', 'New York', 'New York', "Men's Apparel", 60.0, 900, 540000.0, 162000.0, 0.3, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 6, 0, 0), 'Northeast', 'New York', 'New York', "Women's Apparel", 50.0, 1000, 500000.0, 125000.0, 0.25, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 7, 0, 0), 'Northeast', 'New York', 'New York', "Men's Street Footwear", 50.0, 1250, 625000.0, 312500.0, 0.5, 'In-store', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 8, 0, 0), 'Northeast', 'New York', 'New York', "Men's Athletic Footwear", 50.0, 900, 450000.0, 135000.0, 0.3, 'Outlet', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 21, 0, 0), 'Northeast', 'New York', 'New York', "Women's Street Footwear", 40.0, 950, 380000.0, 133000.0, 0.35, 'Outlet', 1, 2020)
('Foot Locker', 1185732, datetime.datetime(2020, 1, 22, 0, 0), 'Northeast', 'New York', 'New York', "Women's Athletic Footwear", 45.0, 825, 371250.0, 129937.49999999999, 0.35, 'Outlet', 1, 2020)

In [ ]:
#Task A h sort the records
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM Adidas ORDER BY `Price per Unit` DESC LIMIT 10"))
    sorted_df = pd.DataFrame(result.fetchall(), columns=result.keys())
sorted_df

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Month,Year
0,West Gear,1128299,2021-06-17,South,Louisiana,New Orleans,Women's Apparel,110.0,750,825000.0,288750.00,0.35,Online,6,2021
1,West Gear,1128299,2021-07-16,South,Louisiana,New Orleans,Women's Apparel,110.0,650,715000.0,250250.00,0.35,Online,7,2021
2,Walmart,1128299,2021-06-17,Southeast,Florida,Orlando,Women's Apparel,110.0,750,825000.0,371250.00,0.45,In-store,6,2021
3,Walmart,1128299,2021-07-16,Southeast,Florida,Orlando,Women's Apparel,110.0,650,715000.0,321750.00,0.45,In-store,7,2021
4,Foot Locker,1128299,2021-06-24,Southeast,Virginia,Richmond,Women's Apparel,105.0,700,735000.0,220500.00,0.30,In-store,6,2021
5,Foot Locker,1128299,2021-07-23,Southeast,Virginia,Richmond,Women's Apparel,105.0,600,630000.0,189000.00,0.30,In-store,7,2021
6,West Gear,1128299,2021-07-23,West,Oregon,Portland,Women's Apparel,105.0,600,630000.0,189000.00,0.30,In-store,7,2021
7,West Gear,1128299,2021-06-24,West,Oregon,Portland,Women's Apparel,105.0,700,735000.0,220500.00,0.30,In-store,6,2021
8,Walmart,1128299,2021-06-17,Southeast,Florida,Orlando,Women's Apparel,103.0,218,22454.0,12574.24,0.56,Online,6,2021
9,West Gear,1128299,2021-07-16,South,Louisiana,New Orleans,Women's Apparel,103.0,163,16789.0,8058.72,0.48,Online,7,2021

In [ ]:
#Task A i count the number of records in the table
with engine.connect() as connection:
    result = connection.execute(text("SELECT COUNT(*) FROM Adidas")).scalar()
print(result)

9648

In [ ]:
#Task A j perform grouping
# Grouping query
with engine.connect() as connection:
    # Group by city and calculate total units sold and total profit
    query = """
    SELECT City,
           SUM(`Units Sold`) AS total_units_sold,
           SUM(`Operating Profit`) AS total_operating_profit
    FROM Adidas
    GROUP BY City
    """
    result = connection.execute(text(query))
    # Fetch all rows
    rows = result.fetchall()

# Print results
for row in rows:
    print(row)

('New York', Decimal('111954'), 13899973.160000006)
('Houston', Decimal('90322'), 9845141.059999993)
('San Francisco', Decimal('86900'), 10256249.560000006)
('Los Angeles', Decimal('76384'), 9044920.84000001)
('Chicago', Decimal('25407'), 3920368.6099999985)
('Dallas', Decimal('69178'), 8843063.29)
('Philadelphia', Decimal('27662'), 4156739.250000001)
('Las Vegas', Decimal('51831'), 7060651.920000003)
('Denver', Decimal('41378'), 7713555.830000001)
('Seattle', Decimal('46611'), 6991403.129999998)
('Miami', Decimal('73135'), 12168619.110000001)
('Minneapolis', Decimal('20838'), 2670229.7600000007)
('Billings', Decimal('42713'), 6232037.550000003)
('Knoxville', Decimal('66077'), 8493660.060000002)
('Omaha', Decimal('19154'), 2439478.4100000006)
('Birmingham', Decimal('63327'), 9147581.39)
('Portland', Decimal('72946'), 10760799.369999994)
('Anchorage', Decimal('30815'), 4498345.860000001)
('Honolulu', Decimal('40375'), 5849794.069999998)
('Orlando', Decimal('60295'), 8757587.810000002)
('Albany', Decimal('57186'), 9429850.91)
('Cheyenne', Decimal('50228'), 6544071.149999999)
('Richmond', Decimal('52969'), 7719430.6800000025)
('Detroit', Decimal('50095'), 8135894.019999998)
('St. Louis', Decimal('36404'), 3907209.3600000013)
('Salt Lake City', Decimal('48548'), 3873429.1000000015)
('New Orleans', Decimal('57615'), 9417233.49)
('Boise', Decimal('63827'), 8121115.099999999)
('Phoenix', Decimal('46919'), 5344664.579999996)
('Albuquerque', Decimal('52633'), 6738060.409999998)
('Atlanta', Decimal('56391'), 6893289.609999999)
('Charleston', Decimal('102483'), 15607190.110000003)
('Charlotte', Decimal('62936'), 9756422.87)
('Columbus', Decimal('47781'), 7528840.0900000045)
('Louisville', Decimal('28664'), 3935830.23)
('Jackson', Decimal('56814'), 6369094.729999999)
('Little Rock', Decimal('48468'), 4915697.910000004)
('Oklahoma City', Decimal('40459'), 4106532.1399999997)
('Wichita', Decimal('29463'), 3510147.2900000014)
('Sioux Falls', Decimal('22973'), 2943318.2100000004)
('Fargo', Decimal('22781'), 2688519.7200000007)
('Des Moines', Decimal('23446'), 2655217.370000001)
('Milwaukee', Decimal('23950'), 2800830.0899999994)
('Indianapolis', Decimal('26332'), 3379256.000000001)
('Baltimore', Decimal('20818'), 2757642.1200000015)
('Wilmington', Decimal('30275'), 4524350.059999998)
('Newark', Decimal('26540'), 3657237.2199999997)
('Hartford', Decimal('34696'), 4152320.7899999996)
('Providence', Decimal('27473'), 3045817.2600000007)
('Boston', Decimal('32895'), 3353875.869999998)
('Burlington', Decimal('38685'), 5785966.49)
('Manchester', Decimal('40812'), 5786206.429999999)

In [ ]:
# Task A k execute update operations on table
# define the update query
update_query = """
UPDATE Adidas
SET `Price per Unit` = `Price per Unit` * 1.1
WHERE Product IN ("Men's Street Footwear", "Women's Street Footwear")
"""

# perform update and commit
with engine.connect() as connection:
    connection.execute(text(update_query))
    connection.commit()
    if result.rowcount > 0:
        print(f"updated {result.rowcount} rows")
    else:
        print("failed to update")

updated 52 rows

In [ ]:
# TaskB a
df_after.to_json('output.json', orient='records')

In [ ]:
pip install schedule

Requirement already satisfied: schedule in /usr/local/lib/python3.10/dist-packages (1.2.2)

In [ ]:
import os
from datetime import datetime,timedelta
import shutil
import time
from google.colab import files
import schedule

In [ ]:
# TaskB b
# upload the locally stored file to google drive

upload_file = files.upload()

Saving output.json to output.json

In [ ]:
file_name = input("Enter the file name: ")

# Checks if the file exists
if os.path.isfile(file_name):
    print(f"{file_name} exists.")
else:
    print(f"{file_name} does not exist.")

Enter the file name: output.json
output.json exists.

In [ ]:
# Get the current working directory
current_path = os.getcwd()
print("Current working directory is:", current_path)

# Specify the root directory for the destination
target_dir_root = '/content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup'

# Get the current time and generate a unique suffix
unique_suffix = datetime.now().strftime("%Y%m%d%H%M%S")
# Construct the backup directory name and path
bucket_name = f'612A2_BACKUP_{unique_suffix}'
backup_path = os.path.join(target_dir_root, bucket_name)

# Output the backup path for verification
print("Backup directory path is:", backup_path)

Current working directory is: /content
Backup directory path is: /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/612A2_BACKUP_20240727051423

In [ ]:
# Check whether the target directory exists. If it does not exist, create it
if not os.path.exists(backup_path):
    os.makedirs(backup_path)
    print(f"Directory '{backup_path}' created successfully.")
else:
    print(f"Directory '{backup_path}' already exists.")

Directory '/content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/612A2_BACKUP_20240727051423' created successfully.

In [ ]:
# Build the source and destination file paths
source_file = os.path.join(current_path, file_name)
target_file = os.path.join(backup_path, file_name)
print(f"Source file: {source_file}")
print(f"Target file: {target_file}")

Source file: /content/output.json
Target file: /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/612A2_BACKUP_20240727051423/output.json

In [ ]:
if os.path.isfile(source_file):
    shutil.copy(source_file, target_file)
    print(f"The file has been copied to: {target_file}")
else:
    print(f"file does not exist: {source_file}")

The file has been copied to: /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/612A2_BACKUP_20240727051423/output.json

In [ ]:
# Backup all file
all_items = os.listdir(current_path)
files = [item for item in all_items if os.path.isfile(os.path.join(current_path, item))]

In [ ]:
# Copy each file to the backup directory
for file_name in files:
    source_file = os.path.join(current_path, file_name)
    target_file = os.path.join(backup_path, file_name)
    shutil.copy(source_file, target_file)
    print(f"Copied {file_name} to {backup_path}")

print("All files have been copied.")

Copied output.json to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/612A2_BACKUP_20240727051423
All files have been copied.

In [ ]:
def backup_files(source_dir, backup_path):
    try:
        os.makedirs(backup_path, exist_ok=True)
        print(f"Backup directory created or already exists: {backup_path}")

        all_items = os.listdir(source_dir)
        print(f"Found {len(all_items)} items in source directory: {source_dir}")

        for item in all_items:
            source_item = os.path.join(source_dir, item)
            target_item = os.path.join(backup_path, item)

            try:
                if os.path.isfile(source_item):
                    shutil.copy(source_item, target_item)
                    print(f"Copied {item} to {backup_path}")
                elif os.path.isdir(source_item):
                    shutil.copytree(source_item, target_item)
                    print(f"Copied directory {item} to {backup_path}")
                else:
                    print(f"Skipping {source_item} as it is not a file or directory.")
            except PermissionError:
                print(f"Permission denied: {source_item}")
            except FileNotFoundError:
                print(f"File not found: {source_item}")
            except Exception as e:
                print(f"Error copying {source_item}: {e}")

        print("Backup process completed.")

    except Exception as e:
        print(f"Error creating backup directory or listing items: {e}")

def schedule_backup(source_dir, target_dir_root, target_hour, target_minute, target_second):
    while True:
        now = datetime.now()
        if (now.hour == target_hour and
            now.minute == target_minute and
            now.second == target_second):

            unique_suffix = now.strftime("%Y%m%d%H%M%S")
            backup_path = os.path.join(target_dir_root, f'BACKUP_{unique_suffix}')

            try:
                backup_files(source_dir, backup_path)
                print("Backup completed and task finished.")
                break
            except Exception as e:
                print(f"Backup failed: {e}")
                break

        time.sleep(1)

# Pass the parameters
source_dir = '/content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup'
target_dir_root = '/content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup'
target_hour = 9
target_minute = 9
target_second = 59

schedule_backup(source_dir, target_dir_root, target_hour, target_minute, target_second)

Backup directory created or already exists: /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Found 10 items in source directory: /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup
Copied directory BACKUP_20240726111512 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory 612A2_BACKUP_20240727051423 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727064159 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied Adidas US Sales Datasets.xlsx to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied output.json to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727064559 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727065359 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727082559 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727082859 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Copied directory BACKUP_20240727090959 to /content/drive/MyDrive/612 course/612 assessment 2/612 A2 backup/BACKUP_20240727090959
Backup process completed.
Backup completed and task finished.